### ISSUE TITLE
Please Help A320 MCDU (PCB LED)

### ISSUE THREAD

**Issue by MrGinseng** [MobiFlight/mobiflight-panels#100]
On the board for the A320 MCDU I have a small problem with the power supply of the LED for the pushbutton switches. When I plug in the 12 volt source and measure with the multimeter, there are 12 volts at the point for the LED, shouldn't this value be lower thrugh the resistors? 

Thank's for this great project and hopefully quick help.

Best regards 

Chris

**Comment by tigert** [comment]
Hey @MrGinseng, my apologies for not noticing this earlier.

To my understanding there are 4 leds in series (and multiple groups of these 4 leds in parallel) so each led gets 12V divided by four between the leds and the resistor.
