### ISSUE TITLE
help - com/radio panel and FENIX A320

### ISSUE THREAD

**Issue by umancuso** [MobiFlight/mobiflight-panels#114]
dears,
I've built a COM panel and a NAV panel and both works flawless with all of the MSFS2020 aircrafts, including FBW A320NX and PMDG 737.

with FENIX A320 both the radios are totally unresponsive - no buttons/encoders working, black displays.

Any hints?

**Comment by tigert** [comment]
Hello, this is actually a config issue and needs the fenixquartz helper app. PLease join Discord and ask on #msfs2020 channel, its a bit off topic here :-)

(and we are much better at responding to requests there than here, it appears.. :-/ )
