### ISSUE TITLE
9.7.1.1 Installer. Modal dialog with release notes sometimes hidden, MF hangs waiting.

### ISSUE THREAD

**Issue by Gamma36** [MobiFlight/mobiflight-panels#117]
After unzipping to a folder and starting MF.exe a modal dialog pops up with release notes, which is very useful.

However the modal dialog can sometimes be hidden and the user just sees the Mobiflight main window hanging with no response. It's tempting for a novice to kill MF at that point.

Switching to another app and back the modal dialog becomes visible, the workflow then progresses normally. However I only spotted this when I saw two MF window icons on the TaskBar.

I suspect there is a problem in the Z ordering of the main windows and modal dialog(s). I know from Windows development there is a Z order for windows, with top most windows like Task Manager with the highest Z-value. I've developed with MFC /C++ and modal dialogs were reliable, there was a message pump to keep everything working well. But I have no idea how C# handles window Z-order in modal dialogs.

I consider this a bug, as the average user can be confused wondering why MF is not responding.

**Comment by ssewell** [comment]
It looks like you're reporting an issue with MobiFlight Connector. This is the repo for sim panels designed to work with MobiFlight. If you're still encountering this problem, you can submit an issue here: https://github.com/MobiFlight/MobiFlight-Connector/issues
