### ISSUE TITLE
Some Questions with with the SCREEN

### ISSUE THREAD

**Issue by KMC-Workshop2024** [MobiFlight/mobiflight-panels#134]

**Comment by KMC-Workshop2024** [comment]
It will be better if there is a screen size details add in README.

**Comment by datamann** [comment]
You can create it and make a pr.

**Comment by KMC-Workshop2024** [comment]
> You can create it and make a pr.

Hmmmm if I know the size of the screen, I will do that :)
but actually I don't really know what model of the screen I should buy 

Could you tell me what model of screen I should buy? Thanks a lot :)

**Comment by KMC-Workshop2024** [comment]
> You can create it and make a pr.

It would be even better if you could guide me in making the MCDU, and provide a list of your raw materials when making the MCDU. :)

Here is my email address:george20070301@gmail.com 

Hope you have a nice day.

**Comment by datamann** [comment]
I used this screen for my MCDU
https://www.aliexpress.com/item/1005001705520738.html
