### ISSUE TITLE
MCDU STL file is not properly generated?

### ISSUE THREAD

**Issue by KissmanCZ** [MobiFlight/mobiflight-panels#85]
Hi, everyone, correct me if I am wrong but I think that A320 MCDU STL is not properly "joined" from multiple parts... so buttons will not work with this MCDU panel.

![image](https://user-images.githubusercontent.com/13331823/152679642-9088e7ac-7f2c-4bcd-91e2-0fdc8b3165dd.png)

**Comment by ssewell** [comment]
Commenting here for those not on Discord. The issue has been confirmed and will be fixed in an update to the STL.
